version: "3.7"

services:
    php:
        build: ./docker/php-fpm
        volumes:
            - .:/var/www/html
        depends_on:
            - mysql
    web:
        image: nginx:latest
        ports:
            - "8888:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/site-host.conf:/etc/nginx/conf.d/default.conf
            - ./var/log/nginx:/var/log/nginx
        depends_on:
            - php
