app_rest_v1:
    resource: "../src/Controller/V1"
    prefix: /v1
    type: annotation

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
